### ISSUE TITLE
Kanban board

### ISSUE THREAD

**Issue by farouqdaif1** [farouqdaif1/CapstoneJS#21]
We are 2 partners in this project  
link for our GitHub project https://github.com/farouqdaif1/CapstoneJS/projects/1

**Comment by helman101** [comment]
# STATUS: CHANGES REQUIRED ♻️ 🔴 

Hi @farouqdaif1  & @aakbarkhan   👋, 

Nice job so far with this project 😄, but there are still some changes to do.

### To Highlight 🌟

- Good job assigning with equality the tasks 👍 

## Required Changes ♻️

- [ ] _Check the comments under the review._

Cheers and Happy coding!👏👏👏

![gif](https://media.giphy.com/media/13HgwGsXF0aiGY/giphy.gif)

If anything is not 100% clear please leave your questions or comments in the PR thread, we will be glad to help you 😄.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by helman101** [comment]
- [ ] Please delete the default cards on your project, they are not necessary for this project 😄
 
    ![imagen](https://user-images.githubusercontent.com/60789317/142902901-fdd3e3e7-f05f-4e61-9a20-b9e049cc153a.png)

**Comment by farouqdaif1** [comment]
I removed the default cards on project

**Comment by mikethreels** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 :
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
